# adapted from https://github.com/purcell/nix-emacs-ci
language: nix

os:
  - linux

env:
  - EMACS_CI=emacs-27-1
  - EMACS_CI=emacs-snapshot

install:
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - cask install
  - which cask
script:
  - make test